// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnuoFlZUGX7-mky8B1C7TywGk6OB84Phw',
    appId: '1:1006069592577:web:7d376da3939c9e6a79c600',
    messagingSenderId: '1006069592577',
    projectId: 'ethostrack-25e86',
    authDomain: 'ethostrack-25e86.firebaseapp.com',
    storageBucket: 'ethostrack-25e86.firebasestorage.app',
    measurementId: 'G-R9MEBBZ5DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtlQl94lkP6Ob74L71jU4csvYKk0yeDcM',
    appId: '1:1006069592577:android:f5f8e81da92744c779c600',
    messagingSenderId: '1006069592577',
    projectId: 'ethostrack-25e86',
    storageBucket: 'ethostrack-25e86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJaKg4mMMGPhaz7Md_BoxOx9T3AHdQWJw',
    appId: '1:1006069592577:ios:9e10e085f064e82b79c600',
    messagingSenderId: '1006069592577',
    projectId: 'ethostrack-25e86',
    storageBucket: 'ethostrack-25e86.firebasestorage.app',
    iosBundleId: 'com.example.ethostrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJaKg4mMMGPhaz7Md_BoxOx9T3AHdQWJw',
    appId: '1:1006069592577:ios:9e10e085f064e82b79c600',
    messagingSenderId: '1006069592577',
    projectId: 'ethostrack-25e86',
    storageBucket: 'ethostrack-25e86.firebasestorage.app',
    iosBundleId: 'com.example.ethostrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnuoFlZUGX7-mky8B1C7TywGk6OB84Phw',
    appId: '1:1006069592577:web:976b62578219127379c600',
    messagingSenderId: '1006069592577',
    projectId: 'ethostrack-25e86',
    authDomain: 'ethostrack-25e86.firebaseapp.com',
    storageBucket: 'ethostrack-25e86.firebasestorage.app',
    measurementId: 'G-HVMP87K2D6',
  );
}
