name: ethostrack
description: "A habits app in Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  flutter_svg: ^2.2.0
  google_fonts: ^6.3.0
  percent_indicator: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter_native_splash:
  color: "#0077B6"
  image: assets/images/logo.png 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
